### ISSUE TITLE
Create a fast, accessible WordPress theme

### ISSUE THREAD

**Issue by ratulkhan74** [cadentcom/pico-wp-block-theme#1]
Many WordPress themes are slow, bloated and lack accessible features. We're going to create a new WordPress theme that demonstrates how quickly a WordPress site can load, while being accessible.

To test our theme, we'll use Google Lighthouse. Our goal is to score 100 x 4 for both mobile and desktop.

_**The theme should include the following elements:**_

- Logo or branding in the upper left corner
- A hierarchical main menu on the header
- No page builders! Gutenberg blocks only
- Support for a hero image
- Featured images for interior pages (optional)
- A footer with a secondary menu.

**Comment by stratofax** [comment]
The text of this Issue is now part of the repo's [README](https://github.com/cadentcom/pico-wp-block-theme/blob/main/README.md) file, so we can close this issue.
