### ISSUE TITLE
Update directory structure in repo

### ISSUE THREAD

**Issue by stratofax** [cadentcom/pico-wp-block-theme#14]
The theme files should be in a sub-directory of the repo's root directory, like this

- pico-wp-block-theme (repo root)
  - src
    - pico-wp-block
       - parts
       - templates

**Comment by ratulkhan74** [comment]
@stratofax I am little bit confused that why we will use the src directory coz we used the recommended structure from wordpress. But i will make the structure

**Comment by stratofax** [comment]
Simply move the structure recommended by WordPress **inside** the `src` directory. Please wait until we've closed #13 first, though.

**Comment by stratofax** [comment]
Based on discussions with @ratulkhan74, we decided this makes testing more difficult. We're therefore dropping this Issue: closed!
