### ISSUE TITLE
Installation instructions and file(s)

### ISSUE THREAD

**Issue by stratofax** [cadentcom/pico-wp-block-theme#15]
This repo should include a section in `README.md` file that includes instructions on how to install the theme files.

**Comment by ratulkhan74** [comment]
@stratofax  After completed the theme we have to create a documentation to submit the theme on wordpress.org. Without the documentation theme won't be able to approve on the wordpress.org

**Comment by stratofax** [comment]
I understand. But before we do that, we need to be able to install the theme in a fresh copy of WordPress for our testing purposes. I want you to write up installation instructions for that. I also suggested that we create a ZIP file of the theme **before** we submit to WordPress.org to test the installation as well.

**Comment by stratofax** [comment]
Please complete #14 first before you start working on this Issue, since organizing the theme files in the repo into a separate sub-directory will make it easier to install the theme files.

**Comment by ratulkhan74** [comment]
@stratofax Installation instructions added in the README.md file and PR created
