### ISSUE TITLE
Use `rem` for all sizes

### ISSUE THREAD

**Issue by stratofax** [cadentcom/pico-wp-block-theme#19]
Font sizes are specified in a mix of  `px` and `em`. Let's use `rem` (root em) unless there's a specific reason not to use `rem`

**Comment by ratulkhan74** [comment]
@stratofax font-size unit has changed

**Comment by stratofax** [comment]
@ratulkhan74 Please link this to #24

**Comment by ratulkhan74** [comment]
@stratofax done

**Comment by stratofax** [comment]
I've changed the title of this issue to reflect our goal to use `rem` for all sizes, not just fonts. See discussion #25 for details.
