### ISSUE TITLE
Create HTML-only base template

### ISSUE THREAD

**Issue by stratofax** [cadentcom/pico-wp-block-theme#2]
Create a code-only block theme with no external reference. Score 100 x 4 on Google Lighthouse. Pass automated HTML testing or linting.

Images may be used as placeholders

**Comment by stratofax** [comment]
It looks like we can generate this with the [Block theme generator from Full Site Editing](https://fullsiteediting.com/block-theme-generator/)

**Comment by ratulkhan74** [comment]
@stratofax  Placeholder image will be used in downloadable theme file.

**Comment by stratofax** [comment]
We need to create that downloadable file, as noted in PR #15, but we don't need to add it to finish our first draft of the Pico block theme.

**Comment by stratofax** [comment]
Issue closed with merge of PR #13
