### ISSUE TITLE
No color, can't see sections of the page

### ISSUE THREAD

**Issue by stratofax** [cadentcom/pico-wp-block-theme#21]
Let's add color to the `<header` and `<footer>` elements so we can see them.

**Comment by ratulkhan74** [comment]
@stratofax do you want me to add background color in header and footer section?

**Comment by stratofax** [comment]
@ratulkhan74 yes, please add a color or gradient. You can use the cadent.com palette.

**Comment by ratulkhan74** [comment]
@stratofax Done

**Comment by stratofax** [comment]
@ratulkhan74 I don't like the colors without the full palette, but it's OK for now. But, the footer should extend to the bottom of the viewport.

**Comment by stratofax** [comment]
@ratulkhan74 Also please link this issue to the appropriate PR!

**Comment by ratulkhan74** [comment]
> @ratulkhan74 I don't like the colors without the full palette, but it's OK for now. But, the footer should extend to the bottom of the viewport.

@stratofax we will gradually fix header and footer color issues. We need to pickup a design idea and according to the design we have to select colors then we will change the color from header and footer

**Comment by stratofax** [comment]
@ratulkhan74 I agree, these colors are good enough for PR #24
