### ISSUE TITLE
pico theme demo test

### ISSUE THREAD

**Issue by ratulkhan74** [cadentcom/pico-wp-block-theme#4]
@stratofax here is the theme test initial result for the demo theme i have added in WIKI section also

**pico-theme-demo  URL:**
https://pico-theme.rk-theme.com/

### **Speed test screenshots**
--------------------------------
**_Mobile:_**
![pico-theme-speed-test-for-mobile](https://github.com/cadentcom/pico-theme/assets/51952371/503624ca-f836-451f-a060-d4dfaaada7f7)

**_Desktop:_**
![pico-theme-speed-test-for-desktop](https://github.com/cadentcom/pico-theme/assets/51952371/543183a6-257a-4e21-92be-5c9200c903f1)

**Comment by stratofax** [comment]
Since you duplicated these images to the Wiki, I'm going to close this issue.
